-- AUTO-GENERATED by scripts/build_sqlite_schema.py -- DO NOT EDIT BY HAND.
-- Source: supabase/migrations/*.sql (50 files) -> SQLite DDL.
-- pgvector match_* / VIEW / FUNCTION 은 core/db 어댑터로 대체됨.
-- 재생성: python scripts/build_sqlite_schema.py
PRAGMA foreign_keys=OFF;

CREATE TABLE decisions (
  id TEXT  PRIMARY KEY,
  market TEXT NOT NULL DEFAULT 'KRW-BTC',
  decision TEXT NOT NULL CHECK (decision IN ('매수', '매도', '관망')),
  confidence REAL,
  reason TEXT NOT NULL,
  market_data_snapshot TEXT,
  fear_greed_value INTEGER,
  rsi_value REAL,
  current_price BIGINT,
  sma20_price BIGINT,
  trade_amount BIGINT,
  trade_volume REAL,
  executed BOOLEAN DEFAULT FALSE,
  execution_result TEXT,
  profit_loss REAL,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_decisions_created_at ON decisions(created_at DESC);

CREATE INDEX idx_decisions_market ON decisions(market);

CREATE INDEX idx_decisions_decision ON decisions(decision);

CREATE TABLE portfolio_snapshots (
  id TEXT  PRIMARY KEY,
  total_krw BIGINT NOT NULL,
  total_crypto_value BIGINT NOT NULL,
  total_value BIGINT NOT NULL,
  holdings TEXT NOT NULL,
  daily_return REAL,
  cumulative_return REAL,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_portfolio_created_at ON portfolio_snapshots(created_at DESC);

CREATE TABLE market_data (
  id TEXT  PRIMARY KEY,
  market TEXT NOT NULL DEFAULT 'KRW-BTC',
  price BIGINT NOT NULL,
  volume_24h REAL,
  change_rate_24h REAL,
  fear_greed_value INTEGER,
  fear_greed_class TEXT,
  rsi_14 REAL,
  sma_20 BIGINT,
  news_sentiment TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_market_data_created_at ON market_data(created_at DESC);

CREATE TABLE feedback (
  id TEXT  PRIMARY KEY,
  type TEXT NOT NULL CHECK (type IN ('parameter_change', 'behavior_change', 'one_time', 'general')),
  content TEXT NOT NULL,
  applied BOOLEAN DEFAULT FALSE,
  applied_at TEXT,
  expires_at TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_feedback_applied ON feedback(applied);

CREATE INDEX idx_feedback_type ON feedback(type);

CREATE TABLE execution_logs (
  id TEXT  PRIMARY KEY,
  execution_mode TEXT NOT NULL CHECK (execution_mode IN ('analyze', 'execute', 'dry_run')),
  decision_id TEXT REFERENCES decisions(id),
  duration_ms INTEGER,
  data_sources TEXT,
  errors TEXT,
  raw_output TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_execution_logs_created_at ON execution_logs(created_at DESC);

CREATE TABLE strategy_history (
  id TEXT  PRIMARY KEY,
  version INTEGER NOT NULL,
  content TEXT NOT NULL,
  change_summary TEXT,
  changed_by TEXT DEFAULT 'user',
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_strategy_history_version ON strategy_history(version DESC);

CREATE TABLE scalp_trades (
  id TEXT  PRIMARY KEY,
  strategy TEXT NOT NULL CHECK (strategy IN ('news', 'spike', 'whale')),
  side TEXT NOT NULL CHECK (side IN ('bid', 'ask')),
  entry_price BIGINT NOT NULL,
  exit_price BIGINT,
  amount_krw INTEGER NOT NULL,
  btc_qty REAL NOT NULL,
  entry_time TEXT NOT NULL,
  exit_time TEXT,
  exit_reason TEXT,
  pnl_pct REAL,
  pnl_krw INTEGER,
  confidence REAL,
  signal_reason TEXT,
  dry_run BOOLEAN DEFAULT TRUE,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_scalp_trades_entry ON scalp_trades(entry_time DESC);

CREATE INDEX idx_scalp_trades_strategy ON scalp_trades(strategy);

CREATE INDEX idx_scalp_trades_pnl ON scalp_trades(pnl_pct);

CREATE TABLE whale_detections (
  id TEXT  PRIMARY KEY,
  side TEXT NOT NULL CHECK (side IN ('BID', 'ASK')),
  volume REAL NOT NULL,
  price BIGINT NOT NULL,
  krw_amount BIGINT NOT NULL,
  detected_at TEXT NOT NULL,
  
  whale_buy_count INTEGER,   
  whale_sell_count INTEGER,  
  buy_ratio REAL,    
  triggered_trade BOOLEAN DEFAULT FALSE,  
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_whale_detected_at ON whale_detections(detected_at DESC);

CREATE INDEX idx_whale_side ON whale_detections(side);

CREATE INDEX idx_whale_amount ON whale_detections(krw_amount DESC);

CREATE TABLE news_sentiment_log (
  id TEXT  PRIMARY KEY,
  sentiment TEXT NOT NULL CHECK (sentiment IN ('positive', 'negative', 'neutral')),
  score REAL NOT NULL,        
  prev_sentiment TEXT,                 
  source TEXT DEFAULT 'rss',           
  headline_count INTEGER,              
  positive_count INTEGER,
  negative_count INTEGER,
  urgent_headlines TEXT,              
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_news_sentiment_created ON news_sentiment_log(created_at DESC);

CREATE INDEX idx_news_sentiment_score ON news_sentiment_log(score);

CREATE TABLE strategy_alerts (
  id TEXT  PRIMARY KEY,
  alert_type TEXT NOT NULL CHECK (alert_type IN (
    'rsi_oversold', 'rsi_extreme_oversold', 'rsi_overbought',
    'whale_buy_reversal', 'whale_sell_pressure',
    'price_spike', 'price_crash',
    'support_break', 'resistance_break',
    'news_extreme',
    'emergency_stop'
  )),
  message TEXT NOT NULL,
  price BIGINT,
  indicator_value REAL,       
  sound_played BOOLEAN DEFAULT FALSE,
  telegram_sent BOOLEAN DEFAULT FALSE,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_strategy_alerts_created ON strategy_alerts(created_at DESC);

CREATE INDEX idx_strategy_alerts_type ON strategy_alerts(alert_type);

CREATE TABLE scalp_sessions (
  id TEXT  PRIMARY KEY,
  start_time TEXT NOT NULL,
  end_time TEXT,
  duration_min INTEGER,
  mode TEXT NOT NULL CHECK (mode IN ('dry_run', 'live')),
  total_trades INTEGER DEFAULT 0,
  wins INTEGER DEFAULT 0,
  losses INTEGER DEFAULT 0,
  win_rate REAL,
  total_pnl_krw INTEGER DEFAULT 0,
  budget INTEGER NOT NULL,
  
  start_price BIGINT,
  end_price BIGINT,
  price_change_pct REAL,
  whale_count INTEGER DEFAULT 0,
  news_sentiment_avg REAL,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_scalp_sessions_start ON scalp_sessions(start_time DESC);

CREATE TABLE ai_signal_log (
  id TEXT  PRIMARY KEY,
  composite_score INTEGER NOT NULL,     
  interpretation TEXT NOT NULL,          
  orderbook_imbalance INTEGER,
  trade_pressure INTEGER,
  whale_direction INTEGER,
  tf_divergence INTEGER,
  volatility_regime INTEGER,
  volume_anomaly INTEGER,
  price BIGINT,
  details TEXT,                         
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_ai_signal_created ON ai_signal_log(created_at DESC);

CREATE INDEX idx_ai_signal_score ON ai_signal_log(composite_score);

CREATE TABLE trade_reviews (
  id TEXT  PRIMARY KEY,
  decision_id TEXT NOT NULL REFERENCES decisions(id),
  
  entry_price BIGINT NOT NULL,                
  exit_price BIGINT,                          
  entry_at TEXT NOT NULL,              
  exit_at TEXT,                        
  
  profit_loss_krw BIGINT DEFAULT 0,           
  profit_loss_pct REAL DEFAULT 0,    
  holding_hours REAL,                
  
  entry_rsi REAL,
  entry_fgi INTEGER,
  entry_sma20_deviation REAL,        
  entry_news_sentiment TEXT,
  
  max_profit_pct REAL,               
  max_drawdown_pct REAL,             
  exit_reason TEXT,                           
  was_correct BOOLEAN,                        
  lesson TEXT,                                
  
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed', 'cancelled')),
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_trade_reviews_decision ON trade_reviews(decision_id);

CREATE INDEX idx_trade_reviews_status ON trade_reviews(status);

CREATE INDEX idx_trade_reviews_entry_at ON trade_reviews(entry_at DESC);

CREATE INDEX idx_trade_reviews_profit ON trade_reviews(profit_loss_pct);

CREATE TABLE agent_switches (
  id TEXT  PRIMARY KEY,
  from_agent TEXT NOT NULL,
  to_agent TEXT NOT NULL,
  reason TEXT NOT NULL,

  
  fgi_at_switch INTEGER,
  rsi_at_switch REAL,
  price_at_switch BIGINT,
  price_change_24h REAL,
  kimchi_premium REAL,
  fusion_signal TEXT,            
  consecutive_losses INTEGER DEFAULT 0,

  
  price_after_4h BIGINT,         
  price_after_24h BIGINT,        
  profit_after_4h REAL,  
  profit_after_24h REAL, 
  outcome TEXT,                  
  outcome_reason TEXT,           

  evaluated_at TEXT,      
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_agent_switches_created ON agent_switches(created_at DESC);

CREATE INDEX idx_agent_switches_outcome ON agent_switches(outcome);

CREATE INDEX idx_agent_switches_agents ON agent_switches(from_agent, to_agent);

CREATE TABLE IF NOT EXISTS scalp_trade_log (
  id TEXT  PRIMARY KEY,
  session_date DATE NOT NULL,
  trade_no INTEGER NOT NULL,                
  strategy TEXT NOT NULL,                    
  entry_time TEXT NOT NULL,
  exit_time TEXT,
  entry_price BIGINT NOT NULL,
  exit_price BIGINT,
  amount_krw INTEGER NOT NULL,
  pnl_pct REAL,
  pnl_krw INTEGER,
  exit_reason TEXT,
  signal_reason TEXT,                        
  confidence REAL,
  
  market_trend TEXT,                         
  news_sentiment TEXT,                       
  news_score REAL,
  fgi_value INTEGER,
  rsi_value REAL,
  sma20_vs_price TEXT,                       
  
  was_good_trade BOOLEAN,                    
  lesson TEXT,                               
  dry_run BOOLEAN DEFAULT TRUE,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_scalp_trade_log_date ON scalp_trade_log(session_date DESC);

CREATE INDEX idx_scalp_trade_log_strategy ON scalp_trade_log(strategy);

CREATE INDEX idx_scalp_trade_log_pnl ON scalp_trade_log(pnl_krw);

CREATE TABLE IF NOT EXISTS external_signal_log (
  id TEXT  PRIMARY KEY,
  recorded_at TEXT DEFAULT CURRENT_TIMESTAMP,
  
  binance_score INTEGER,
  long_short_ratio REAL,
  funding_rate REAL,
  open_interest_change REAL,
  
  whale_score INTEGER,
  whale_flow TEXT,
  large_tx_count INTEGER,
  exchange_inflow REAL,
  exchange_outflow REAL,
  
  macro_score INTEGER,
  sp500_change REAL,
  dxy_change REAL,
  gold_change REAL,
  us10y_change REAL,
  
  fgi_value INTEGER,
  fgi_classification TEXT,
  news_sentiment REAL,
  news_score INTEGER,
  news_count INTEGER,
  
  eth_btc_ratio REAL,
  eth_btc_score INTEGER,
  eth_btc_trend TEXT,
  
  coingecko_score INTEGER,
  volume_anomaly BOOLEAN,
  volume_change_pct REAL,
  
  kimchi_premium_pct REAL,
  
  fusion_score INTEGER,
  fusion_signal TEXT,
  fusion_details TEXT,
  
  source TEXT DEFAULT 'agent',
  session_type TEXT
);

CREATE INDEX idx_ext_signal_recorded ON external_signal_log(recorded_at DESC);

CREATE INDEX idx_ext_signal_fusion ON external_signal_log(fusion_signal);

CREATE TABLE IF NOT EXISTS buy_score_detail (
  id TEXT  PRIMARY KEY,
  decision_id TEXT,
  recorded_at TEXT DEFAULT CURRENT_TIMESTAMP,
  
  agent_type TEXT NOT NULL,
  threshold INTEGER NOT NULL,
  
  fgi_score REAL,
  fgi_value INTEGER,
  rsi_score REAL,
  rsi_value REAL,
  sma_score REAL,
  sma_position TEXT,
  news_score REAL,
  news_sentiment REAL,
  external_bonus REAL,
  external_signal TEXT,
  
  total_score REAL NOT NULL,
  
  action TEXT NOT NULL,
  buy_amount INTEGER,
  sell_pct REAL,
  confidence REAL,
  reason TEXT,
  
  btc_price BIGINT,
  market_trend TEXT,
  adx_regime TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_buy_score_recorded ON buy_score_detail(recorded_at DESC);

CREATE INDEX idx_buy_score_agent ON buy_score_detail(agent_type);

CREATE INDEX idx_buy_score_action ON buy_score_detail(action);

CREATE TABLE IF NOT EXISTS market_context_log (
  id TEXT  PRIMARY KEY,
  decision_id TEXT,
  recorded_at TEXT DEFAULT CURRENT_TIMESTAMP,
  
  btc_price BIGINT,
  btc_24h_change REAL,
  btc_volume REAL,
  
  rsi_14 REAL,
  sma_20 BIGINT,
  sma_vs_price TEXT,
  macd_value REAL,
  macd_signal REAL,
  macd_histogram REAL,
  bb_upper BIGINT,
  bb_lower BIGINT,
  bb_position TEXT,
  adx_value REAL,
  adx_regime TEXT,
  
  fgi_value INTEGER,
  fgi_class TEXT,
  news_sentiment REAL,
  news_positive INTEGER,
  news_negative INTEGER,
  news_neutral INTEGER,
  
  funding_rate REAL,
  long_short_ratio REAL,
  open_interest REAL,
  oi_change_pct REAL,
  kimchi_premium REAL,
  
  whale_flow TEXT,
  large_tx_count INTEGER,
  exchange_net_flow REAL,
  
  sp500_trend TEXT,
  dxy_trend TEXT,
  gold_trend TEXT,
  macro_sentiment TEXT,
  
  eth_btc_ratio REAL,
  eth_btc_trend TEXT,
  
  krw_balance BIGINT,
  btc_balance REAL,
  btc_avg_price BIGINT,
  total_asset_value BIGINT,
  position_ratio REAL,
  
  active_agent TEXT,
  danger_score INTEGER,
  opportunity_score INTEGER,
  
  raw_data TEXT
);

CREATE INDEX idx_mkt_ctx_recorded ON market_context_log(recorded_at DESC);

CREATE INDEX idx_mkt_ctx_decision ON market_context_log(decision_id);

ALTER TABLE decisions ADD COLUMN cycle_id TEXT;

ALTER TABLE decisions ADD COLUMN source TEXT DEFAULT 'unknown';

ALTER TABLE portfolio_snapshots ADD COLUMN cycle_id TEXT;

ALTER TABLE market_data ADD COLUMN cycle_id TEXT;

ALTER TABLE execution_logs ADD COLUMN cycle_id TEXT;

ALTER TABLE external_signal_log ADD COLUMN cycle_id TEXT;

ALTER TABLE buy_score_detail ADD COLUMN cycle_id TEXT;

ALTER TABLE market_context_log ADD COLUMN cycle_id TEXT;

ALTER TABLE agent_switches ADD COLUMN cycle_id TEXT;

ALTER TABLE scalp_trades ADD COLUMN cycle_id TEXT;

ALTER TABLE scalp_trade_log ADD COLUMN cycle_id TEXT;

ALTER TABLE scalp_sessions ADD COLUMN cycle_id TEXT;

ALTER TABLE ai_signal_log ADD COLUMN cycle_id TEXT;

ALTER TABLE whale_detections ADD COLUMN cycle_id TEXT;

ALTER TABLE news_sentiment_log ADD COLUMN cycle_id TEXT;

CREATE INDEX IF NOT EXISTS idx_decisions_cycle ON decisions(cycle_id);

CREATE INDEX IF NOT EXISTS idx_portfolio_cycle ON portfolio_snapshots(cycle_id);

CREATE INDEX IF NOT EXISTS idx_market_data_cycle ON market_data(cycle_id);

CREATE INDEX IF NOT EXISTS idx_exec_logs_cycle ON execution_logs(cycle_id);

CREATE INDEX IF NOT EXISTS idx_ext_signal_cycle ON external_signal_log(cycle_id);

CREATE INDEX IF NOT EXISTS idx_buy_score_cycle ON buy_score_detail(cycle_id);

CREATE INDEX IF NOT EXISTS idx_mkt_ctx_cycle ON market_context_log(cycle_id);

CREATE INDEX IF NOT EXISTS idx_agent_switch_cycle ON agent_switches(cycle_id);

CREATE INDEX IF NOT EXISTS idx_scalp_trades_cycle ON scalp_trades(cycle_id);

CREATE INDEX IF NOT EXISTS idx_scalp_trade_log_cycle ON scalp_trade_log(cycle_id);

CREATE INDEX IF NOT EXISTS idx_scalp_sessions_cycle ON scalp_sessions(cycle_id);

CREATE INDEX IF NOT EXISTS idx_ai_signal_cycle ON ai_signal_log(cycle_id);

CREATE INDEX IF NOT EXISTS idx_whale_cycle ON whale_detections(cycle_id);

CREATE INDEX IF NOT EXISTS idx_news_sentiment_cycle ON news_sentiment_log(cycle_id);

CREATE INDEX IF NOT EXISTS idx_decisions_source ON decisions(source);

CREATE INDEX IF NOT EXISTS idx_decisions_date_source ON decisions(((created_at )), source);

ALTER TABLE decisions ADD COLUMN price_1h_after BIGINT;

ALTER TABLE decisions ADD COLUMN price_4h_after BIGINT;

ALTER TABLE decisions ADD COLUMN price_24h_after BIGINT;

ALTER TABLE decisions ADD COLUMN outcome_1h_pct REAL;

ALTER TABLE decisions ADD COLUMN outcome_4h_pct REAL;

ALTER TABLE decisions ADD COLUMN outcome_24h_pct REAL;

ALTER TABLE decisions ADD COLUMN was_correct_1h BOOLEAN;

ALTER TABLE decisions ADD COLUMN was_correct_4h BOOLEAN;

ALTER TABLE decisions ADD COLUMN was_correct_24h BOOLEAN;

ALTER TABLE decisions ADD COLUMN aftermath_updated_at TEXT;

ALTER TABLE scalp_trade_log ADD COLUMN price_1h_after BIGINT;

ALTER TABLE scalp_trade_log ADD COLUMN outcome_1h_pct REAL;

ALTER TABLE scalp_trade_log ADD COLUMN was_good_entry BOOLEAN;

ALTER TABLE scalp_trade_log ADD COLUMN aftermath_updated_at TEXT;

CREATE INDEX IF NOT EXISTS idx_decisions_no_1h ON decisions(created_at DESC) WHERE price_1h_after IS NULL;

CREATE INDEX IF NOT EXISTS idx_decisions_no_4h ON decisions(created_at DESC) WHERE price_4h_after IS NULL;

CREATE INDEX IF NOT EXISTS idx_decisions_no_24h ON decisions(created_at DESC) WHERE price_24h_after IS NULL;

CREATE INDEX IF NOT EXISTS idx_scalp_no_aftermath ON scalp_trade_log(entry_time DESC) WHERE price_1h_after IS NULL;

CREATE TABLE IF NOT EXISTS signal_attempt_log (
  id TEXT  PRIMARY KEY,
  recorded_at TEXT DEFAULT CURRENT_TIMESTAMP,
  cycle_id TEXT,
  
  strategy TEXT NOT NULL,
  signal_type TEXT NOT NULL CHECK (signal_type IN ('generated', 'blocked', 'no_signal')),
  action TEXT,
  confidence REAL,
  suggested_amount INTEGER,
  signal_reason TEXT,
  
  block_filter TEXT,
  block_reason TEXT,
  
  btc_price BIGINT,
  market_trend TEXT,
  rsi_value REAL,
  fgi_value INTEGER,
  news_score REAL,
  
  price_1h_after BIGINT,
  outcome_1h_pct REAL,
  would_have_won BOOLEAN,
  aftermath_updated_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_signal_attempt_recorded ON signal_attempt_log(recorded_at DESC);

CREATE INDEX IF NOT EXISTS idx_signal_attempt_type ON signal_attempt_log(signal_type);

CREATE INDEX IF NOT EXISTS idx_signal_attempt_strategy ON signal_attempt_log(strategy);

CREATE INDEX IF NOT EXISTS idx_signal_attempt_blocked ON signal_attempt_log(recorded_at DESC) WHERE signal_type = 'blocked';

CREATE INDEX IF NOT EXISTS idx_signal_attempt_no_aftermath ON signal_attempt_log(recorded_at DESC) WHERE price_1h_after IS NULL AND signal_type != 'no_signal';

ALTER TABLE buy_score_detail ADD COLUMN points_from_threshold REAL;

ALTER TABLE buy_score_detail ADD COLUMN is_near_miss BOOLEAN DEFAULT FALSE;

ALTER TABLE buy_score_detail ADD COLUMN was_ai_vetoed BOOLEAN DEFAULT FALSE;

ALTER TABLE buy_score_detail ADD COLUMN ai_veto_reason TEXT;

ALTER TABLE buy_score_detail ADD COLUMN original_action TEXT;

ALTER TABLE buy_score_detail ADD COLUMN orchestrator_override BOOLEAN DEFAULT FALSE;

ALTER TABLE buy_score_detail ADD COLUMN override_reason TEXT;

ALTER TABLE buy_score_detail ADD COLUMN price_at_decision BIGINT;

ALTER TABLE buy_score_detail ADD COLUMN price_1h_after BIGINT;

ALTER TABLE buy_score_detail ADD COLUMN price_4h_after BIGINT;

ALTER TABLE buy_score_detail ADD COLUMN outcome_1h_pct REAL;

ALTER TABLE buy_score_detail ADD COLUMN outcome_4h_pct REAL;

ALTER TABLE buy_score_detail ADD COLUMN would_have_profited BOOLEAN;

ALTER TABLE buy_score_detail ADD COLUMN aftermath_updated_at TEXT;

CREATE INDEX IF NOT EXISTS idx_buy_score_near_miss ON buy_score_detail(is_near_miss) WHERE is_near_miss = true;

CREATE INDEX IF NOT EXISTS idx_buy_score_vetoed ON buy_score_detail(was_ai_vetoed) WHERE was_ai_vetoed = true;

CREATE INDEX IF NOT EXISTS idx_buy_score_no_aftermath ON buy_score_detail(recorded_at DESC) WHERE price_1h_after IS NULL;

ALTER TABLE execution_logs ADD COLUMN execution_started_at TEXT;

ALTER TABLE execution_logs ADD COLUMN execution_completed_at TEXT;

ALTER TABLE execution_logs ADD COLUMN success BOOLEAN;

ALTER TABLE execution_logs ADD COLUMN error_phase TEXT;

ALTER TABLE execution_logs ADD COLUMN error_code TEXT;

ALTER TABLE execution_logs ADD COLUMN error_message TEXT;

ALTER TABLE execution_logs ADD COLUMN retry_count INTEGER DEFAULT 0;

ALTER TABLE execution_logs ADD COLUMN phases_completed TEXT;

ALTER TABLE decisions ADD COLUMN execution_attempted BOOLEAN;

ALTER TABLE decisions ADD COLUMN execution_started_at TEXT;

ALTER TABLE decisions ADD COLUMN execution_completed_at TEXT;

ALTER TABLE decisions ADD COLUMN execution_latency_ms INTEGER;

CREATE INDEX IF NOT EXISTS idx_exec_logs_success ON execution_logs(success) WHERE success = false;

CREATE INDEX IF NOT EXISTS idx_exec_logs_error ON execution_logs(error_phase);

CREATE INDEX IF NOT EXISTS idx_decisions_exec_attempted ON decisions(execution_attempted);

ALTER TABLE decisions ADD COLUMN state_embedding BLOB;

ALTER TABLE decisions ADD COLUMN embedding_text TEXT;

ALTER TABLE decisions ADD COLUMN external_signal_id TEXT REFERENCES external_signal_log(id);

ALTER TABLE decisions ADD COLUMN buy_score_id TEXT REFERENCES buy_score_detail(id);

CREATE INDEX IF NOT EXISTS idx_decisions_ext_signal ON decisions(external_signal_id);

CREATE INDEX IF NOT EXISTS idx_decisions_buy_score ON decisions(buy_score_id);

CREATE TABLE IF NOT EXISTS rag_analysis_vectors (
    id TEXT  PRIMARY KEY,
    cycle_id TEXT,
    decision_id TEXT REFERENCES decisions(id) ON DELETE SET NULL,
    analysis_text TEXT NOT NULL,
    analysis_json TEXT,
    market_regime TEXT,
    embedding BLOB,
    gemini_model TEXT DEFAULT 'gemini-2.5-pro',
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_rag_analysis_created
    ON rag_analysis_vectors (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_rag_analysis_cycle
    ON rag_analysis_vectors (cycle_id);

CREATE INDEX IF NOT EXISTS idx_rag_analysis_regime
    ON rag_analysis_vectors (market_regime);

CREATE TABLE IF NOT EXISTS rl_training_log (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at      TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

    
    tier            TEXT NOT NULL,           
    tier_name       TEXT,                    
    steps           INTEGER NOT NULL,        
    data_days       INTEGER NOT NULL,        
    lr_ratio        REAL NOT NULL,           
    candles_count   INTEGER,                 

    
    baseline_return_pct  REAL,
    baseline_sharpe      REAL,
    baseline_mdd         REAL,
    baseline_trades      REAL,

    
    new_return_pct       REAL,
    new_sharpe           REAL,
    new_mdd              REAL,
    new_trades           REAL,

    
    improved        BOOLEAN NOT NULL,        
    version_id      TEXT,                    
    elapsed_sec     REAL,                    
    rollback        BOOLEAN DEFAULT FALSE,   

    
    notes           TEXT                     
);

CREATE INDEX idx_rl_training_tier ON rl_training_log(tier);

CREATE INDEX idx_rl_training_created ON rl_training_log(created_at DESC);

CREATE TABLE IF NOT EXISTS rl_training_results (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    trainer_id      TEXT NOT NULL,                
    algorithm       TEXT NOT NULL DEFAULT 'ppo',  
    
    training_days   INT NOT NULL DEFAULT 180,
    training_steps  INT NOT NULL DEFAULT 100000,
    interval        TEXT NOT NULL DEFAULT '1h',
    edge_cases      BOOLEAN DEFAULT FALSE,
    synthetic_ratio FLOAT DEFAULT 0.0,
    
    avg_return_pct  FLOAT NOT NULL,
    avg_sharpe      FLOAT,
    avg_mdd         FLOAT,
    avg_trades      FLOAT,
    
    observation_dim INT DEFAULT 42,
    model_hash      TEXT,                         
    model_url       TEXT,                         
    
    best_return_pct FLOAT,                        
    improvement     FLOAT,                        
    
    status          TEXT DEFAULT 'submitted',     
    review_note     TEXT,                         
    promoted_at     TEXT,                  
    created_at      TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at      TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_training_results_trainer ON rl_training_results(trainer_id);

CREATE INDEX idx_training_results_status ON rl_training_results(status);

CREATE INDEX idx_training_results_return ON rl_training_results(avg_return_pct DESC);

CREATE TABLE IF NOT EXISTS system_health_logs (
    id                  TEXT PRIMARY KEY ,
    "timestamp"           TEXT DEFAULT CURRENT_TIMESTAMP,
    component           TEXT NOT NULL,
    severity            TEXT NOT NULL DEFAULT 'INFO'
                        CHECK (severity IN ('INFO', 'WARNING', 'ERROR', 'CRITICAL')),
    issue_summary       TEXT NOT NULL,
    raw_traceback       TEXT,
    ai_diagnosis        TEXT,
    healing_action      TEXT,
    resolution_status   TEXT DEFAULT 'DETECTED'
                        CHECK (resolution_status IN (
                            'DETECTED', 'DIAGNOSING', 'HEALING',
                            'RESOLVED', 'FAILED', 'PENDING'
                        )),
    healing_duration_ms INTEGER,
    created_at          TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_health_logs_timestamp ON system_health_logs("timestamp" DESC);

CREATE INDEX idx_health_logs_component ON system_health_logs(component);

CREATE INDEX idx_health_logs_severity ON system_health_logs(severity);

CREATE INDEX idx_health_logs_resolution ON system_health_logs(resolution_status);

CREATE TABLE IF NOT EXISTS rl_training_cycles (
    id              TEXT PRIMARY KEY ,
    
    cycle_type      TEXT NOT NULL,              
    algorithm       TEXT NOT NULL,              
    module          TEXT NOT NULL,              
    
    training_steps  INT,
    training_epochs INT,
    data_days       INT,
    data_count      INT,                        
    interval        TEXT DEFAULT '4h',           
    obs_dim         INT DEFAULT 42,
    morl_enabled    BOOLEAN DEFAULT FALSE,
    
    avg_return_pct  FLOAT,
    avg_sharpe      FLOAT,
    avg_mdd         FLOAT,
    avg_trades      FLOAT,
    policy_loss     FLOAT,
    value_loss      FLOAT,
    entropy         FLOAT,
    
    direction_accuracy FLOAT,                   
    q_loss          FLOAT,
    cql_penalty     FLOAT,
    
    best_eval_loss  FLOAT,
    n_sequences     INT,
    context_length  INT,
    
    model_version   TEXT,                        
    model_path      TEXT,
    status          TEXT NOT NULL DEFAULT 'completed', 
    error_message   TEXT,
    
    baseline_sharpe FLOAT,                       
    improved        BOOLEAN,                     
    
    started_at      TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at    TEXT,
    elapsed_seconds FLOAT,
    created_at      TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_tc_cycle_type ON rl_training_cycles(cycle_type);

CREATE INDEX idx_tc_algorithm ON rl_training_cycles(algorithm);

CREATE INDEX idx_tc_module ON rl_training_cycles(module);

CREATE INDEX idx_tc_status ON rl_training_cycles(status);

CREATE INDEX idx_tc_created_at ON rl_training_cycles(created_at DESC);

CREATE INDEX idx_tc_algorithm_created ON rl_training_cycles(algorithm, created_at DESC);

CREATE TABLE IF NOT EXISTS rl_model_predictions (
    id              TEXT PRIMARY KEY ,
    
    decision_id     TEXT REFERENCES decisions(id) ON DELETE SET NULL,
    cycle_id        TEXT,                        
    
    ensemble_action FLOAT,                       
    ensemble_direction TEXT,                     
    num_models      INT,                         
    
    sb3_action      FLOAT,                       
    sb3_version     TEXT,                        
    dt_action       FLOAT,                       
    dt_version      TEXT,
    multi_agent_action FLOAT,                    
    multi_agent_direction TEXT,                   
    multi_agent_scalp_action FLOAT,              
    multi_agent_swing_action FLOAT,              
    offline_action  FLOAT,                       
    offline_version TEXT,
    
    btc_price       FLOAT,
    rsi_14          FLOAT,
    fgi             INT,
    danger_score    FLOAT,
    opportunity_score FLOAT,
    
    price_after_4h  FLOAT,
    price_after_24h FLOAT,
    return_after_4h FLOAT,                       
    return_after_24h FLOAT,
    prediction_quality TEXT,                     
    
    predicted_at    TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at      TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_mp_decision_id ON rl_model_predictions(decision_id);

CREATE INDEX idx_mp_cycle_id ON rl_model_predictions(cycle_id);

CREATE INDEX idx_mp_ensemble_dir ON rl_model_predictions(ensemble_direction);

CREATE INDEX idx_mp_predicted_at ON rl_model_predictions(predicted_at DESC);

CREATE INDEX idx_mp_quality ON rl_model_predictions(prediction_quality);

CREATE TABLE IF NOT EXISTS rl_model_versions (
    id              TEXT PRIMARY KEY ,
    version_id      TEXT NOT NULL UNIQUE,         
    algorithm       TEXT NOT NULL,                
    model_path      TEXT,
    
    sharpe_ratio    FLOAT,
    total_return_pct FLOAT,
    max_drawdown    FLOAT,
    eval_episodes   INT,
    
    training_steps  INT,
    training_days   INT,
    training_config TEXT,                        
    
    is_active       BOOLEAN DEFAULT FALSE,        
    is_best         BOOLEAN DEFAULT FALSE,        
    
    live_trades     INT DEFAULT 0,
    live_win_rate   FLOAT,
    live_avg_return FLOAT,
    live_start_date TEXT,
    
    notes           TEXT,
    promoted_from   TEXT,                         
    rollback_count  INT DEFAULT 0,
    retired_at      TEXT,                  
    created_at      TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at      TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_mv_version ON rl_model_versions(version_id);

CREATE INDEX idx_mv_algorithm ON rl_model_versions(algorithm);

CREATE INDEX idx_mv_active ON rl_model_versions(is_active);

CREATE INDEX idx_mv_sharpe ON rl_model_versions(sharpe_ratio DESC );

CREATE INDEX idx_mv_created ON rl_model_versions(created_at DESC);

CREATE TABLE IF NOT EXISTS rl_parameter_tuning (
    id              TEXT PRIMARY KEY ,
    
    parameter_name  TEXT NOT NULL,                
    old_value       FLOAT,
    new_value       FLOAT,
    change_reason   TEXT,                         
    
    before_sharpe   FLOAT,
    after_sharpe    FLOAT,
    before_return   FLOAT,
    after_return    FLOAT,
    
    approved        BOOLEAN,                     
    rolled_back     BOOLEAN DEFAULT FALSE,
    rollback_reason TEXT,
    
    tuned_at        TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at      TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_pt_param ON rl_parameter_tuning(parameter_name);

CREATE INDEX idx_pt_tuned_at ON rl_parameter_tuning(tuned_at DESC);

CREATE INDEX idx_pt_reason ON rl_parameter_tuning(change_reason);

CREATE TABLE IF NOT EXISTS kimchirang_trades (
  id TEXT  PRIMARY KEY,
  action TEXT NOT NULL CHECK (action IN ('enter', 'exit', 'stop_loss', 'error')),
  kp_at_execution REAL NOT NULL,
  entry_kp REAL,
  exit_kp REAL,
  pnl_pct REAL,

  
  upbit_order_id TEXT,
  upbit_side TEXT,
  upbit_price BIGINT,
  upbit_qty REAL,

  
  binance_order_id TEXT,
  binance_side TEXT,
  binance_price REAL,
  binance_qty REAL,

  
  fx_rate REAL,
  funding_rate REAL,
  spread_cost REAL,
  latency_ms INTEGER,
  dry_run BOOLEAN DEFAULT TRUE,
  both_success BOOLEAN,
  hold_duration_min REAL,

  
  kp_stats TEXT,

  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_kimchirang_trades_created ON kimchirang_trades(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_kimchirang_trades_action ON kimchirang_trades(action);

ALTER TABLE decisions ADD COLUMN dry_run boolean DEFAULT false;

CREATE TABLE IF NOT EXISTS kimchirang_kp_history (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  mid_kp REAL NOT NULL,
  entry_kp REAL,
  exit_kp REAL,
  kp_ma_1m REAL,
  kp_ma_5m REAL,
  kp_z_score REAL,
  kp_velocity REAL,
  spread_cost REAL,
  funding_rate REAL,
  upbit_bid BIGINT,
  upbit_ask BIGINT,
  binance_bid REAL,
  binance_ask REAL,
  fx_rate REAL,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_kr_kp_history_created ON kimchirang_kp_history(created_at DESC);

CREATE TABLE IF NOT EXISTS kimchirang_rl_models (
  id TEXT  PRIMARY KEY,
  model_name TEXT NOT NULL,
  version TEXT NOT NULL,
  training_days INTEGER,
  training_steps INTEGER,
  eval_pnl_pct REAL,
  eval_trades INTEGER,
  eval_reward REAL,
  kp_data_range TEXT,           
  kp_min REAL,
  kp_max REAL,
  kp_mean REAL,
  hyperparams TEXT,            
  notes TEXT,
  deployed BOOLEAN DEFAULT FALSE,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS kimchirang_sessions (
  id TEXT  PRIMARY KEY,
  start_time TEXT NOT NULL,
  end_time TEXT,
  mode TEXT DEFAULT 'dry_run',  
  rl_model_version TEXT,
  total_trades INTEGER DEFAULT 0,
  total_pnl_pct REAL DEFAULT 0,
  best_trade_pnl REAL,
  worst_trade_pnl REAL,
  avg_hold_min REAL,
  avg_kp_entry REAL,
  avg_kp_exit REAL,
  errors INTEGER DEFAULT 0,
  notes TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE kimchirang_trades ADD COLUMN session_id TEXT REFERENCES kimchirang_sessions(id);

ALTER TABLE kimchirang_trades ADD COLUMN rl_action INTEGER;

ALTER TABLE kimchirang_trades ADD COLUMN rl_confidence REAL;

ALTER TABLE kimchirang_trades ADD COLUMN rule_action INTEGER;

ALTER TABLE kimchirang_trades ADD COLUMN kp_ma_5m REAL;

ALTER TABLE kimchirang_trades ADD COLUMN kp_z_score REAL;

CREATE INDEX IF NOT EXISTS idx_kr_trades_session ON kimchirang_trades(session_id);

CREATE TABLE IF NOT EXISTS app_changelog (
  id TEXT  PRIMARY KEY,
  version TEXT NOT NULL,                
  severity TEXT NOT NULL CHECK (severity IN ('critical', 'major', 'minor', 'patch')),
  category TEXT NOT NULL CHECK (category IN ('bugfix', 'feature', 'improvement', 'refactor', 'config', 'strategy')),
  summary TEXT NOT NULL,                
  details TEXT,                        
  files_modified TEXT,                
  verified BOOLEAN DEFAULT FALSE,       
  verification_result TEXT,             
  changed_by TEXT DEFAULT 'claude_session',
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_app_changelog_version ON app_changelog(version);

CREATE INDEX idx_app_changelog_created_at ON app_changelog(created_at DESC);

CREATE INDEX idx_app_changelog_severity ON app_changelog(severity);

CREATE TABLE IF NOT EXISTS scalp_market_snapshot (
  id TEXT  PRIMARY KEY,
  recorded_at TEXT DEFAULT CURRENT_TIMESTAMP,
  cycle_id TEXT,
  
  btc_price BIGINT NOT NULL,
  
  rsi_1h REAL,
  sma20 BIGINT,
  market_trend TEXT,                    
  
  fgi INTEGER,
  news_sentiment TEXT,
  news_score REAL,
  
  whale_buy_count INTEGER DEFAULT 0,
  whale_sell_count INTEGER DEFAULT 0,
  whale_buy_krw BIGINT DEFAULT 0,
  whale_sell_krw BIGINT DEFAULT 0,
  whale_buy_ratio REAL,        
  
  trade_buy_volume REAL,      
  trade_sell_volume REAL,     
  trade_pressure_ratio REAL,   
  
  momentum_1m_pct REAL,        
  momentum_5m_pct REAL,        
  momentum_15m_pct REAL,       
  
  volatility_5m REAL,          
  
  open_positions INTEGER DEFAULT 0,
  daily_trade_count INTEGER DEFAULT 0,
  daily_pnl_krw INTEGER DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_scalp_snapshot_recorded ON scalp_market_snapshot(recorded_at DESC);

CREATE INDEX IF NOT EXISTS idx_scalp_snapshot_trend ON scalp_market_snapshot(market_trend, recorded_at DESC);

ALTER TABLE signal_attempt_log ADD COLUMN price_1m_after BIGINT;

ALTER TABLE signal_attempt_log ADD COLUMN price_5m_after BIGINT;

ALTER TABLE signal_attempt_log ADD COLUMN price_15m_after BIGINT;

ALTER TABLE signal_attempt_log ADD COLUMN price_30m_after BIGINT;

ALTER TABLE signal_attempt_log ADD COLUMN outcome_1m_pct REAL;

ALTER TABLE signal_attempt_log ADD COLUMN outcome_5m_pct REAL;

ALTER TABLE signal_attempt_log ADD COLUMN outcome_15m_pct REAL;

ALTER TABLE signal_attempt_log ADD COLUMN outcome_30m_pct REAL;

ALTER TABLE signal_attempt_log ADD COLUMN would_have_won_5m BOOLEAN;

ALTER TABLE signal_attempt_log ADD COLUMN would_have_won_15m BOOLEAN;

ALTER TABLE signal_attempt_log ADD COLUMN would_have_won_30m BOOLEAN;

ALTER TABLE signal_attempt_log ADD COLUMN best_price_30m BIGINT;

ALTER TABLE signal_attempt_log ADD COLUMN worst_price_30m BIGINT;

ALTER TABLE signal_attempt_log ADD COLUMN best_exit_pct REAL;

ALTER TABLE signal_attempt_log ADD COLUMN worst_drawdown_pct REAL;

ALTER TABLE signal_attempt_log ADD COLUMN momentum_1m_pct REAL;

ALTER TABLE signal_attempt_log ADD COLUMN whale_buy_ratio REAL;

ALTER TABLE signal_attempt_log ADD COLUMN trade_pressure_ratio REAL;

ALTER TABLE signal_attempt_log ADD COLUMN volatility_5m REAL;

CREATE INDEX IF NOT EXISTS idx_signal_no_1m ON signal_attempt_log(recorded_at DESC)
  WHERE price_1m_after IS NULL AND signal_type != 'no_signal';

CREATE INDEX IF NOT EXISTS idx_signal_no_5m ON signal_attempt_log(recorded_at DESC)
  WHERE price_5m_after IS NULL AND signal_type != 'no_signal';

CREATE INDEX IF NOT EXISTS idx_signal_no_15m ON signal_attempt_log(recorded_at DESC)
  WHERE price_15m_after IS NULL AND signal_type != 'no_signal';

CREATE INDEX IF NOT EXISTS idx_signal_no_30m ON signal_attempt_log(recorded_at DESC)
  WHERE price_30m_after IS NULL AND signal_type != 'no_signal';

CREATE TABLE IF NOT EXISTS scalp_training_tasks (
  id TEXT  PRIMARY KEY,
  task_type TEXT NOT NULL CHECK (task_type IN (
    'backtest', 'train_lgbm', 'train_xgboost', 'train_pytorch',
    'evaluate', 'parameter_sweep', 'analyze'
  )),
  params TEXT NOT NULL DEFAULT '[]',    
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN (
    'pending', 'running', 'completed', 'failed', 'cancelled'
  )),
  priority INTEGER DEFAULT 5,            
  assigned_worker TEXT,                  
  result TEXT,                          
  error_message TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  started_at TEXT,
  completed_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_training_tasks_status ON scalp_training_tasks(status, priority);

CREATE INDEX IF NOT EXISTS idx_training_tasks_worker ON scalp_training_tasks(assigned_worker, status);

CREATE TABLE IF NOT EXISTS scalp_model_versions (
  id TEXT  PRIMARY KEY,
  version_tag TEXT NOT NULL UNIQUE,       
  model_type TEXT NOT NULL CHECK (model_type IN (
    'lightgbm', 'xgboost', 'pytorch', 'rule_based'
  )),
  
  model_config TEXT,                     
  features_used TEXT,                    
  model_blob BYTEA,                       
  model_path TEXT,                        
  
  train_accuracy REAL,
  test_accuracy REAL,
  train_samples INTEGER,
  test_samples INTEGER,
  precision_score REAL,
  recall_score REAL,
  f1_score REAL,
  
  backtest_return_pct REAL,
  backtest_sharpe REAL,
  backtest_max_drawdown REAL,
  backtest_win_rate REAL,
  backtest_trades INTEGER,
  
  live_trades INTEGER DEFAULT 0,
  live_win_rate REAL,
  live_return_pct REAL,
  
  is_active BOOLEAN DEFAULT FALSE,
  training_task_id TEXT REFERENCES scalp_training_tasks(id),
  promoted_at TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  notes TEXT
);

CREATE INDEX IF NOT EXISTS idx_model_versions_active ON scalp_model_versions(is_active) WHERE is_active = TRUE;

CREATE INDEX IF NOT EXISTS idx_model_versions_type ON scalp_model_versions(model_type, created_at DESC);

ALTER TABLE scalp_trade_log ADD COLUMN model_version TEXT;

ALTER TABLE scalp_trade_log ADD COLUMN model_confidence REAL;

ALTER TABLE scalp_trade_log ADD COLUMN momentum_1m_pct REAL;

ALTER TABLE scalp_trade_log ADD COLUMN whale_buy_ratio REAL;

ALTER TABLE scalp_trade_log ADD COLUMN trade_pressure REAL;

ALTER TABLE scalp_trade_log ADD COLUMN volatility_5m REAL;

ALTER TABLE scalp_trade_log ADD COLUMN trailing_stop_hit BOOLEAN DEFAULT FALSE;

ALTER TABLE scalp_trade_log ADD COLUMN highest_pnl_pct REAL;

ALTER TABLE scalp_trade_log ADD COLUMN grace_period_saved BOOLEAN DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS scalp_settlements (
    id TEXT  PRIMARY KEY,
    epoch INT NOT NULL,
    elapsed_hours REAL,
    period_trades INT DEFAULT 0,
    period_wins INT DEFAULT 0,
    period_losses INT DEFAULT 0,
    period_win_rate REAL,
    period_pnl_krw INT DEFAULT 0,
    estimated_fee_krw INT DEFAULT 0,
    fee_covered BOOLEAN DEFAULT FALSE,
    cumulative_trades INT DEFAULT 0,
    cumulative_pnl_krw INT DEFAULT 0,
    strategy_stats TEXT,
    market_trend TEXT,
    rsi_value REAL,
    fgi_value INT,
    current_price BIGINT,
    dry_run BOOLEAN DEFAULT TRUE,
    cycle_id TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS scalp_training_journal (
    id TEXT  PRIMARY KEY,
    epoch INT NOT NULL,
    elapsed_hours REAL,
    period_summary TEXT,
    cumulative_summary TEXT,
    fee_analysis TEXT,
    strategy_breakdown TEXT,
    market_context TEXT,
    improvement_notes TEXT,
    dry_run BOOLEAN DEFAULT TRUE,
    cycle_id TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_scalp_settlements_cycle ON scalp_settlements(cycle_id);

CREATE INDEX IF NOT EXISTS idx_scalp_settlements_created ON scalp_settlements(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_scalp_journal_cycle ON scalp_training_journal(cycle_id);

CREATE INDEX IF NOT EXISTS idx_scalp_journal_created ON scalp_training_journal(created_at DESC);

CREATE TABLE IF NOT EXISTS compute_workers (
  id TEXT  PRIMARY KEY,
  worker_id TEXT NOT NULL UNIQUE,           
  worker_name TEXT,                          
  tier TEXT NOT NULL DEFAULT 'collaborator' CHECK (tier IN (
    'owner', 'coworker', 'collaborator', 'viewer'
  )),
  
  platform TEXT,                             
  architecture TEXT,                         
  ram_gb INTEGER,                            
  cpu_info TEXT,                             
  gpu_info TEXT,                             
  python_version TEXT,
  
  status TEXT NOT NULL DEFAULT 'offline' CHECK (status IN (
    'online', 'busy', 'offline', 'error', 'suspended'
  )),
  is_main_brain BOOLEAN DEFAULT FALSE,       
  
  last_heartbeat TEXT,
  heartbeat_interval_sec INTEGER DEFAULT 60, 
  
  can_gpu BOOLEAN DEFAULT FALSE,             
  max_concurrent_tasks INTEGER DEFAULT 1,    
  allowed_task_types TEXT ,
  
  tasks_completed INTEGER DEFAULT 0,
  tasks_failed INTEGER DEFAULT 0,
  total_training_hours REAL DEFAULT 0,
  avg_task_duration_sec INTEGER,
  
  registered_at TEXT DEFAULT CURRENT_TIMESTAMP,
  last_online_at TEXT,
  notes TEXT
);

CREATE INDEX IF NOT EXISTS idx_workers_status ON compute_workers(status);

CREATE INDEX IF NOT EXISTS idx_workers_tier ON compute_workers(tier);

CREATE TABLE IF NOT EXISTS worker_heartbeats (
  id TEXT  PRIMARY KEY,
  worker_id TEXT NOT NULL REFERENCES compute_workers(worker_id),
  recorded_at TEXT DEFAULT CURRENT_TIMESTAMP,
  status TEXT NOT NULL,
  
  cpu_usage_pct REAL,
  ram_usage_pct REAL,
  disk_free_gb REAL,
  
  current_task_id TEXT,
  current_task_type TEXT,
  task_progress_pct REAL
);

CREATE INDEX IF NOT EXISTS idx_heartbeats_worker ON worker_heartbeats(worker_id, recorded_at DESC);

ALTER TABLE compute_workers ADD COLUMN api_token TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS uq_compute_workers_api_token ON compute_workers(api_token);

CREATE INDEX IF NOT EXISTS idx_workers_api_token ON compute_workers(api_token);

ALTER TABLE compute_workers ADD COLUMN telegram_chat_id TEXT;

ALTER TABLE compute_workers ADD COLUMN email TEXT;

CREATE TABLE IF NOT EXISTS telegram_messages (
  id TEXT  PRIMARY KEY,
  chat_id TEXT NOT NULL,                
  worker_id TEXT,                        
  worker_name TEXT,                      
  direction TEXT NOT NULL CHECK (direction IN ('incoming', 'outgoing')),
  message TEXT NOT NULL,
  telegram_message_id BIGINT,            
  telegram_username TEXT,                
  telegram_first_name TEXT,              
  is_read BOOLEAN DEFAULT FALSE,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_tg_msg_chat ON telegram_messages(chat_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_tg_msg_unread ON telegram_messages(is_read, direction)
  WHERE NOT is_read AND direction = 'incoming';

CREATE TABLE IF NOT EXISTS telegram_contacts (
  id TEXT  PRIMARY KEY,
  chat_id TEXT NOT NULL UNIQUE,          
  name TEXT NOT NULL,                     
  role TEXT NOT NULL DEFAULT 'friend' CHECK (role IN (
    'owner', 'coworker', 'collaborator', 'viewer', 'friend'
  )),
  email TEXT,
  worker_id TEXT,                         
  is_active BOOLEAN DEFAULT TRUE,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  notes TEXT
);

CREATE INDEX IF NOT EXISTS idx_tg_contacts_role ON telegram_contacts(role);

CREATE INDEX IF NOT EXISTS idx_tg_contacts_chat ON telegram_contacts(chat_id);

CREATE INDEX IF NOT EXISTS idx_decisions_created_at_source
  ON decisions(created_at DESC, source);

CREATE INDEX IF NOT EXISTS idx_market_context_log_decision_id
  ON market_context_log(decision_id, recorded_at);

ALTER TABLE external_signal_log ADD COLUMN decision_id TEXT REFERENCES decisions(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_external_signal_log_decision_id
  ON external_signal_log(decision_id);

ALTER TABLE decisions ADD COLUMN machine_name TEXT;

ALTER TABLE portfolio_snapshots ADD COLUMN machine_name TEXT;

ALTER TABLE agent_switches ADD COLUMN machine_name TEXT;

ALTER TABLE execution_logs ADD COLUMN machine_name TEXT;

ALTER TABLE scalp_trades ADD COLUMN machine_name TEXT;

ALTER TABLE scalp_trade_log ADD COLUMN machine_name TEXT;

ALTER TABLE scalp_sessions ADD COLUMN machine_name TEXT;

ALTER TABLE scalp_settlements ADD COLUMN machine_name TEXT;

ALTER TABLE kimchirang_trades ADD COLUMN machine_name TEXT;

ALTER TABLE kimchirang_kp_history ADD COLUMN machine_name TEXT;

ALTER TABLE external_signal_log ADD COLUMN machine_name TEXT;

ALTER TABLE scalp_training_tasks ADD COLUMN machine_name TEXT;

CREATE INDEX IF NOT EXISTS idx_decisions_machine ON decisions (machine_name);

CREATE INDEX IF NOT EXISTS idx_scalp_trades_machine ON scalp_trades (machine_name);

CREATE INDEX IF NOT EXISTS idx_kimchirang_trades_machine ON kimchirang_trades (machine_name);

CREATE INDEX IF NOT EXISTS idx_scalp_sessions_machine ON scalp_sessions (machine_name);

ALTER TABLE rl_training_cycles ADD COLUMN pnl_24h_after REAL;

ALTER TABLE rl_training_cycles ADD COLUMN pnl_72h_after REAL;

ALTER TABLE rl_training_cycles ADD COLUMN training_meta TEXT DEFAULT '[]';

ALTER TABLE market_data ADD COLUMN machine_name TEXT;

ALTER TABLE market_context_log ADD COLUMN machine_name TEXT;

CREATE INDEX IF NOT EXISTS idx_market_data_machine ON market_data (machine_name);

CREATE INDEX IF NOT EXISTS idx_market_context_log_machine ON market_context_log (machine_name);

ALTER TABLE scalp_market_snapshot ADD COLUMN machine_name TEXT;

ALTER TABLE signal_attempt_log ADD COLUMN machine_name TEXT;

ALTER TABLE news_sentiment_log ADD COLUMN machine_name TEXT;

CREATE INDEX IF NOT EXISTS idx_scalp_market_snapshot_machine ON scalp_market_snapshot(machine_name);

CREATE INDEX IF NOT EXISTS idx_signal_attempt_log_machine ON signal_attempt_log(machine_name);

CREATE TABLE IF NOT EXISTS seonbirang_trades (
  id TEXT  PRIMARY KEY,
  strategy TEXT NOT NULL CHECK (strategy IN ('funding', 'rotation')),
  action TEXT NOT NULL,
  symbol TEXT NOT NULL,
  funding_rate REAL,
  momentum_score REAL,
  pnl_pct REAL,
  pnl_usdt REAL,
  size_usdt REAL,
  reason TEXT,
  dry_run BOOLEAN DEFAULT TRUE,
  success BOOLEAN DEFAULT FALSE,
  machine_name TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sb_trades_created ON seonbirang_trades(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_sb_trades_strategy ON seonbirang_trades(strategy);

CREATE INDEX IF NOT EXISTS idx_sb_trades_symbol ON seonbirang_trades(symbol);

CREATE TABLE IF NOT EXISTS seonbirang_coin_rankings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  scan_type TEXT CHECK (scan_type IN ('funding', 'momentum')),
  rankings TEXT NOT NULL,
  universe_size INTEGER,
  machine_name TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sb_rankings_created ON seonbirang_coin_rankings(created_at DESC);

CREATE TABLE IF NOT EXISTS seonbirang_snapshots (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  total_balance_usdt REAL,
  funding_positions TEXT,
  rotation_positions TEXT,
  funding_count INTEGER,
  rotation_count INTEGER,
  total_funding_collected REAL,
  total_unrealized_pnl REAL,
  machine_name TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sb_snapshots_created ON seonbirang_snapshots(created_at DESC);

ALTER TABLE seonbirang_trades RENAME TO altrang_trades;

ALTER TABLE seonbirang_coin_rankings RENAME TO altrang_coin_rankings;

ALTER TABLE seonbirang_snapshots RENAME TO altrang_snapshots;

CREATE TABLE IF NOT EXISTS newsrang_signals (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at      TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    machine_name    TEXT DEFAULT 'unknown',

    
    collection_time_sec REAL,
    total_articles      INT DEFAULT 0,

    
    rss_crypto_score    INT,          
    rss_macro_score     INT,          
    rss_combined_score  INT,          
    rss_article_count   INT DEFAULT 0,
    rss_feed_errors     TEXT,

    
    x_score             INT,          
    x_signal            TEXT,         
    x_tweet_count       INT DEFAULT 0,
    x_bullish_count     INT DEFAULT 0,
    x_bearish_count     INT DEFAULT 0,
    x_whale_summary     TEXT,        

    
    social_score        INT,          
    social_signal       TEXT,
    social_sources      INT DEFAULT 0,
    social_components   TEXT,        

    
    fusion_total_score  INT,
    fusion_rss_adj      INT,
    fusion_x_adj        INT,
    fusion_social_adj   INT,

    
    rss_top_signals     TEXT,        
    x_top_tweets        TEXT,        
    social_raw          TEXT         
);

CREATE INDEX IF NOT EXISTS idx_newsrang_created ON newsrang_signals(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_newsrang_machine ON newsrang_signals(machine_name);

DROP INDEX IF EXISTS idx_decisions_embedding;

CREATE TABLE IF NOT EXISTS claude_memories (
  id TEXT  PRIMARY KEY,

  
  memory_tier TEXT NOT NULL DEFAULT 'short_term'
    CHECK (memory_tier IN ('short_term', 'long_term')),
  category TEXT NOT NULL
    CHECK (category IN ('user', 'feedback', 'project', 'reference', 'known_issue')),

  
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  summary TEXT,                           
  tags TEXT DEFAULT '[]',
  source_file TEXT,                       

  
  access_count INTEGER DEFAULT 0,
  last_accessed TEXT,
  relevance_score FLOAT DEFAULT 1.0,      
  pinned BOOLEAN DEFAULT FALSE,           

  
  embedding BLOB,                 

  
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
  consolidated_at TEXT,
  consolidated_from TEXT,               

  machine_name TEXT DEFAULT 'mac-mini'
);

CREATE INDEX idx_mem_tier ON claude_memories(memory_tier);

CREATE INDEX idx_mem_category ON claude_memories(category);

CREATE INDEX idx_mem_relevance ON claude_memories(relevance_score DESC);

CREATE INDEX idx_mem_last_accessed ON claude_memories(last_accessed DESC );

CREATE INDEX idx_mem_created ON claude_memories(created_at DESC);

CREATE INDEX idx_mem_pinned ON claude_memories(pinned) WHERE pinned = TRUE;

ALTER TABLE decisions ADD COLUMN model_id TEXT;

ALTER TABLE decisions ADD COLUMN prompt_hash TEXT;

ALTER TABLE decisions ADD COLUMN temperature REAL;

ALTER TABLE decisions ADD COLUMN state_embedding_bge BLOB;

CREATE TABLE IF NOT EXISTS reembedding_status (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  target      text NOT NULL DEFAULT 'decisions.state_embedding_bge',
  status      text NOT NULL DEFAULT 'pending'   
    CHECK (status IN ('pending', 'in_progress', 'completed')),
  total_rows  integer,
  done_rows   integer DEFAULT 0,
  started_at  TEXT,
  completed_at TEXT,
  created_at  TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO reembedding_status (target, status)
SELECT 'decisions.state_embedding_bge', 'pending'
WHERE NOT EXISTS (
  SELECT 1 FROM reembedding_status
   WHERE target = 'decisions.state_embedding_bge'
);


-- ============================================================
-- 수동 DDL (build_sqlite_schema.py 가 자동 생성하지 않는 항목).
-- 변환기가 generated 테이블 뒤에 이 파일을 그대로 append 함.
-- ============================================================

-- performance_reviews: run_analysis.ps1 이 db.select(order=reviewed_at.desc) 로 조회.
-- migration 에 정의 부재(aspirational) -> no such table 회피용 최소 스키마.
CREATE TABLE IF NOT EXISTS performance_reviews (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    reviewed_at     TEXT DEFAULT CURRENT_TIMESTAMP,
    period_start    TEXT,
    period_end      TEXT,
    review_type     TEXT,
    total_evaluated INTEGER,
    wins            INTEGER,
    losses          INTEGER,
    win_rate_pct    REAL,
    avg_profit_loss REAL,
    assessment      TEXT,
    summary         TEXT,
    details         TEXT,
    created_at      TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_perf_reviews_reviewed_at ON performance_reviews(reviewed_at DESC);

-- ============================================================
-- v_* 회상/회고 뷰 (수동 이식: PG migration -> SQLite 호환)
-- 출처: supabase/migrations/009,010,011,012,013,032.
-- build_sqlite_schema.py 는 CREATE VIEW 를 제외하므로 여기 수동 append.
-- 재생성 시 변환기가 이 블록을 덮어쓰지 않음(append-only, header 부터 테이블까지만 생성).
-- 변환 요지: FILTER(WHERE)->SUM(CASE WHEN), LATERAL->상관 서브쿼리,
--   ::numeric/::date->제거/date(), NOW()-INTERVAL->datetime('now',...),
--   SUBSTRING->substr, EXTRACT/ABS 시간차 매칭->decision_id 직접 JOIN(032).
-- ============================================================

-- V1: 단타 거래 전체 맥락 (032 최적화본: decision_id 직접 JOIN + cycle_id fallback)
CREATE VIEW IF NOT EXISTS v_trade_recall AS
SELECT
  d.id AS decision_id,
  d.cycle_id,
  d.source,
  d.created_at,
  d.decision AS action,
  d.confidence,
  d.current_price AS price,
  d.trade_amount,
  d.reason,
  d.profit_loss,
  d.executed,
  bs.total_score AS buy_total,
  bs.fgi_score AS buy_fgi,
  bs.rsi_score AS buy_rsi,
  bs.sma_score AS buy_sma,
  bs.news_score AS buy_news,
  bs.external_bonus AS buy_ext,
  bs.agent_type,
  bs.threshold AS buy_threshold,
  mc.rsi_14,
  mc.sma_20,
  mc.fgi_value,
  mc.fgi_class,
  mc.funding_rate,
  mc.long_short_ratio,
  mc.kimchi_premium,
  mc.whale_flow,
  mc.macro_sentiment,
  mc.eth_btc_trend,
  mc.active_agent,
  mc.danger_score,
  mc.opportunity_score,
  mc.position_ratio,
  COALESCE(es1.fusion_score,    esf.fusion_score)    AS ext_fusion,
  COALESCE(es1.fusion_signal,   esf.fusion_signal)   AS ext_signal,
  COALESCE(es1.binance_score,   esf.binance_score)   AS ext_binance,
  COALESCE(es1.whale_score,     esf.whale_score)     AS ext_whale,
  COALESCE(es1.macro_score,     esf.macro_score)     AS ext_macro,
  COALESCE(es1.coingecko_score, esf.coingecko_score) AS ext_coingecko,
  COALESCE(es1.eth_btc_score,   esf.eth_btc_score)   AS ext_ethbtc
FROM decisions d
LEFT JOIN buy_score_detail bs ON bs.decision_id = d.id
LEFT JOIN market_context_log mc ON mc.decision_id = d.id
LEFT JOIN external_signal_log es1 ON es1.decision_id = d.id
LEFT JOIN external_signal_log esf ON esf.id = (
  SELECT e.id FROM external_signal_log e
  WHERE es1.id IS NULL AND e.decision_id IS NULL AND e.cycle_id = d.cycle_id
  LIMIT 1
)
ORDER BY d.created_at DESC;

-- V2: 초단타 거래 전체 맥락
CREATE VIEW IF NOT EXISTS v_scalp_recall AS
SELECT
  t.id, t.cycle_id, t.session_date, t.trade_no, t.strategy,
  t.entry_time, t.exit_time, t.entry_price, t.exit_price, t.amount_krw,
  t.pnl_pct, t.pnl_krw, t.exit_reason, t.signal_reason, t.confidence,
  t.market_trend, t.news_sentiment, t.news_score, t.fgi_value, t.rsi_value,
  t.sma20_vs_price, t.was_good_trade, t.lesson, t.dry_run
FROM scalp_trade_log t
ORDER BY t.entry_time DESC;

-- V3: 일별 요약
CREATE VIEW IF NOT EXISTS v_daily_summary AS
SELECT
  trade_date,
  total_decisions,
  buys,
  sells,
  holds,
  avg_confidence,
  total_pnl,
  avg_buy_score,
  (SELECT COUNT(*) FROM scalp_trade_log s WHERE s.session_date = sub.trade_date) AS scalp_trades,
  (SELECT SUM(s.pnl_krw) FROM scalp_trade_log s WHERE s.session_date = sub.trade_date) AS scalp_pnl,
  avg_fgi,
  avg_rsi
FROM (
  SELECT
    date(d.created_at) AS trade_date,
    COUNT(*) AS total_decisions,
    SUM(CASE WHEN d.decision = '매수' THEN 1 ELSE 0 END) AS buys,
    SUM(CASE WHEN d.decision = '매도' THEN 1 ELSE 0 END) AS sells,
    SUM(CASE WHEN d.decision = '관망' THEN 1 ELSE 0 END) AS holds,
    ROUND(AVG(d.confidence), 2) AS avg_confidence,
    SUM(d.profit_loss) AS total_pnl,
    ROUND(AVG(bs.total_score), 1) AS avg_buy_score,
    ROUND(AVG(mc.fgi_value), 0) AS avg_fgi,
    ROUND(AVG(mc.rsi_14), 1) AS avg_rsi
  FROM decisions d
  LEFT JOIN buy_score_detail bs ON bs.decision_id = d.id
  LEFT JOIN market_context_log mc ON mc.decision_id = d.id
  GROUP BY date(d.created_at)
) sub
ORDER BY trade_date DESC;

-- V4: cycle 단위 조회 (032 최적화본)
CREATE VIEW IF NOT EXISTS v_cycle_detail AS
SELECT
  d.cycle_id,
  d.source,
  d.created_at,
  d.decision AS action,
  d.current_price AS price,
  d.trade_amount,
  d.confidence,
  d.profit_loss,
  substr(d.reason, 1, 100) AS reason_short,
  bs.total_score,
  bs.agent_type,
  mc.fgi_value,
  mc.rsi_14,
  mc.danger_score,
  mc.opportunity_score,
  COALESCE(es1.fusion_signal, esf.fusion_signal) AS ext_signal,
  COALESCE(es1.fusion_score,  esf.fusion_score)  AS ext_score
FROM decisions d
LEFT JOIN buy_score_detail bs ON bs.decision_id = d.id
LEFT JOIN market_context_log mc ON mc.decision_id = d.id
LEFT JOIN external_signal_log es1 ON es1.decision_id = d.id
LEFT JOIN external_signal_log esf ON esf.id = (
  SELECT e.id FROM external_signal_log e
  WHERE es1.id IS NULL AND e.decision_id IS NULL AND e.cycle_id = d.cycle_id
  LIMIT 1
)
WHERE d.cycle_id IS NOT NULL
ORDER BY d.created_at DESC;

-- 결정 정확도 분석 (010)
CREATE VIEW IF NOT EXISTS v_decision_accuracy AS
SELECT
  decision,
  source,
  COUNT(*) AS total,
  ROUND(AVG(outcome_1h_pct), 2) AS avg_1h_pct,
  SUM(CASE WHEN was_correct_1h = 1 THEN 1 ELSE 0 END) AS correct_1h,
  ROUND(SUM(CASE WHEN was_correct_1h = 1 THEN 1.0 ELSE 0 END)
        / NULLIF(SUM(CASE WHEN was_correct_1h IS NOT NULL THEN 1 ELSE 0 END), 0) * 100, 1) AS accuracy_1h,
  ROUND(AVG(outcome_4h_pct), 2) AS avg_4h_pct,
  SUM(CASE WHEN was_correct_4h = 1 THEN 1 ELSE 0 END) AS correct_4h,
  ROUND(SUM(CASE WHEN was_correct_4h = 1 THEN 1.0 ELSE 0 END)
        / NULLIF(SUM(CASE WHEN was_correct_4h IS NOT NULL THEN 1 ELSE 0 END), 0) * 100, 1) AS accuracy_4h,
  ROUND(AVG(outcome_24h_pct), 2) AS avg_24h_pct,
  SUM(CASE WHEN was_correct_24h = 1 THEN 1 ELSE 0 END) AS correct_24h,
  ROUND(SUM(CASE WHEN was_correct_24h = 1 THEN 1.0 ELSE 0 END)
        / NULLIF(SUM(CASE WHEN was_correct_24h IS NOT NULL THEN 1 ELSE 0 END), 0) * 100, 1) AS accuracy_24h
FROM decisions
WHERE aftermath_updated_at IS NOT NULL
GROUP BY decision, source;

-- 놓친 기회 (010)
CREATE VIEW IF NOT EXISTS v_missed_opportunities AS
SELECT
  id, cycle_id, created_at, current_price,
  outcome_1h_pct, outcome_4h_pct, outcome_24h_pct,
  reason, confidence, fear_greed_value, rsi_value
FROM decisions
WHERE decision = '관망'
  AND outcome_24h_pct > 1.5
  AND aftermath_updated_at IS NOT NULL
ORDER BY outcome_24h_pct DESC;

-- 잘못된 거래 (010)
CREATE VIEW IF NOT EXISTS v_bad_trades AS
SELECT
  id, cycle_id, created_at, current_price, trade_amount,
  outcome_1h_pct, outcome_4h_pct, outcome_24h_pct,
  reason, confidence, fear_greed_value, rsi_value
FROM decisions
WHERE decision = '매수'
  AND outcome_4h_pct < -0.5
  AND aftermath_updated_at IS NOT NULL
ORDER BY outcome_4h_pct ASC;

-- 필터 효과 분석 (011)
CREATE VIEW IF NOT EXISTS v_filter_effectiveness AS
SELECT
  block_filter,
  COUNT(*) AS total_blocked,
  SUM(CASE WHEN would_have_won = 1 THEN 1 ELSE 0 END) AS would_have_won_count,
  SUM(CASE WHEN would_have_won = 0 THEN 1 ELSE 0 END) AS would_have_lost_count,
  ROUND(SUM(CASE WHEN would_have_won = 0 THEN 1.0 ELSE 0 END)
        / NULLIF(SUM(CASE WHEN would_have_won IS NOT NULL THEN 1 ELSE 0 END), 0) * 100, 1) AS filter_save_rate,
  ROUND(AVG(outcome_1h_pct), 2) AS avg_outcome_if_traded
FROM signal_attempt_log
WHERE signal_type = 'blocked' AND aftermath_updated_at IS NOT NULL
GROUP BY block_filter
ORDER BY total_blocked DESC;

-- 니어미스 분석 (012)
CREATE VIEW IF NOT EXISTS v_near_miss_analysis AS
SELECT
  recorded_at,
  agent_type,
  total_score,
  threshold,
  points_from_threshold,
  was_ai_vetoed,
  ai_veto_reason,
  action,
  price_at_decision,
  outcome_1h_pct,
  outcome_4h_pct,
  would_have_profited,
  CASE
    WHEN would_have_profited = 1 AND action = 'hold' THEN '놓친 기회'
    WHEN would_have_profited = 0 AND action = 'hold' THEN '올바른 관망'
    WHEN would_have_profited = 1 AND action IN ('buy', '매수') THEN '좋은 매수'
    WHEN would_have_profited = 0 AND action IN ('buy', '매수') THEN '나쁜 매수'
    ELSE '미평가'
  END AS evaluation
FROM buy_score_detail
WHERE is_near_miss = 1 OR was_ai_vetoed = 1
ORDER BY recorded_at DESC;

-- AI 거부권 효과 분석 (012)
CREATE VIEW IF NOT EXISTS v_ai_veto_effectiveness AS
SELECT
  ai_veto_reason,
  COUNT(*) AS total_vetoes,
  SUM(CASE WHEN would_have_profited = 0 THEN 1 ELSE 0 END) AS saved_from_loss,
  SUM(CASE WHEN would_have_profited = 1 THEN 1 ELSE 0 END) AS missed_profit,
  ROUND(SUM(CASE WHEN would_have_profited = 0 THEN 1.0 ELSE 0 END)
        / NULLIF(SUM(CASE WHEN would_have_profited IS NOT NULL THEN 1 ELSE 0 END), 0) * 100, 1) AS veto_accuracy_pct,
  ROUND(AVG(outcome_4h_pct), 2) AS avg_outcome_if_bought
FROM buy_score_detail
WHERE was_ai_vetoed = 1 AND aftermath_updated_at IS NOT NULL
GROUP BY ai_veto_reason
ORDER BY total_vetoes DESC;

-- 시스템 건강도 (013, 최근 24시간)
CREATE VIEW IF NOT EXISTS v_system_health AS
SELECT
  execution_mode,
  COUNT(*) AS total_runs,
  SUM(CASE WHEN success = 1 THEN 1 ELSE 0 END) AS success_count,
  SUM(CASE WHEN success = 0 THEN 1 ELSE 0 END) AS failure_count,
  ROUND(SUM(CASE WHEN success = 1 THEN 1.0 ELSE 0 END)
        / NULLIF(COUNT(*), 0) * 100, 1) AS success_rate,
  ROUND(AVG(duration_ms), 0) AS avg_duration_ms,
  MAX(duration_ms) AS max_duration_ms,
  MAX(created_at) AS last_run
FROM execution_logs
WHERE created_at > datetime('now', '-24 hours')
GROUP BY execution_mode;
